spring:
  profiles:
    active: dev #默认为开发环境

# swagger
swagger:
  enabled: true
  title: 灵光项目管理 接口文档
  description: 旨在做一个灵活方便的项目管理系统
  version: 1.0.0.RELEASE
  contact.name: hzlgit
  base-package: com.hzlgit.project
  base-path: /api/**, /sign-in, /sign-up,/sign-up/**, /test #指定了swagger可访问的url
  exclude-path: /error, /ops/**