spring:
  profiles:
    active: dev #默认为开发环境

  datasource:
    url: jdbc:mysql://localhost:3308/smartproject?useUnicode=true&characterEncoding=utf8
    username: hzlg
    password: hzlg
    driver-class-name: com.mysql.jdbc.Driver

  # Redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址，默认localhost
    host: 127.0.0.1
    # 端口 默认6379
    port: 6379
    # 密码 默认空
    password:

## Mybatis
mybatis:
  typeAliasesPackage: com.hzlgit.project
  mapperLocations: classpath:mapper/*.xml


# swagger
swagger:
  enabled: true
  title: 灵光项目管理 接口文档
  description: 旨在做一个灵活方便的项目管理系统
  version: 1.0.0.RELEASE
  contact.name: hzlgit
  base-package: com.hzlgit.project
  base-path: /api/**, /sign-in, /sign-up,/sign-up/**, /test #指定了swagger可访问的url
  exclude-path: /error, /ops/**

